output "cluster_id" {
  value       = module.development_cluster.id
  description = "The ID of the cluster generated by this example."
}

output "cluster_endpoint" {
  value       = module.development_cluster.endpoint
  description = "The endpoint of the cluster generated by this example."
}

output "bastion_instance_public_ip" {
  value       = aws_instance.bastion_instance.public_ip
  description = "The public IP address assigned to the bastion instance generated by this example."
}
