output "bucket_name" {
  value       = data.aws_s3_bucket.s3_bucket.id
  description = "The name of the S3 bucket generated by this module."
}

output "bucket_domain_name" {
  value       = data.aws_s3_bucket.s3_bucket.bucket_domain_name
  description = "The domain name of the S3 bucket generated by this module."
}

output "elasticsearch_iam_role_name" {
  value       = aws_iam_role.elasticsearch_domain_iam_role.name
  description = "The name of the elasticsearch service IAM role generated by this module."
}

output "lambda_iam_role_name" {
  value       = aws_iam_role.lambda_iam_role.name
  description = "The name of the lambda IAM role generated by this module."
}

output "lambda_function_name" {
  value       = aws_lambda_function.lambda_function.function_name
  description = "The function name of the lambda generated by this module."
}

output "lambda_cloudwatch_event_rule_name" {
  value       = aws_cloudwatch_event_rule.cloudwatch_event_rule.name
  description = "The name of the cloudwatch event that triggers the lambda function generated by this module."
}

output "query_lambda_function_name" {
  value       = aws_lambda_function.query_lambda_function.function_name
  description = "The function name of the query lambda generated by this module."
}
