output "bucket_name" {
  value       = data.aws_s3_bucket.s3_bucket.id
  description = "The name of the s3 bucket generated by this module."
}

output "bucket_arn" {
  value       = data.aws_s3_bucket.s3_bucket.arn
  description = "The ARN of the s3 bucket generated by this module."
}

output "elasticsearch_bastion_instance_security_group" {
  value       = aws_security_group.elasticsearch_bastion_security_group.id
  description = "The ID of the elasticsearch bastion instance security group generated by this module."
}

output "elasticsearch_bastion_instance_public_ip" {
  value       = aws_instance.elasticsearch_bastion_instance.public_ip
  description = "The public IP address assigned to the elasticsearch bastion instance generated by this module."
}
