output "id" {
  value       = aws_elasticsearch_domain.elasticsearch_domain.domain_id
  description = "The unique identifier of the elasticsearch domain generated by this module."
}

output "arn" {
  value       = aws_elasticsearch_domain.elasticsearch_domain.arn
  description = "The Amazon Resource Name (ARN) of the elasticsearch domain generated by this module."
}

output "name" {
  value       = aws_elasticsearch_domain.elasticsearch_domain.domain_name
  description = "The name of the elasticsearch domain generated by this module."
}

output "endpoint" {
  value       = aws_elasticsearch_domain.elasticsearch_domain.endpoint
  description = "The domain-specific endpoint used to submit index, search, and data upload requests for the elasticsearch domain generated by this module."
}

output "kibana_endpoint" {
  value       = aws_elasticsearch_domain.elasticsearch_domain.kibana_endpoint
  description = "The domain-specific endpoint for kibana without https scheme for the elasticsearch domain generated by this module."
}

output "security_group" {
  value       = aws_security_group.security_group.id
  description = "The ID of the security group of the elasticsearch domain generated by this module."
}
