output "cluster_id" {
  value       = module.development_cluster.id
  description = "The ID of the cluster generated by this example."
}

output "cluster_endpoint" {
  value       = module.development_cluster.endpoint
  description = "The endpoint of the cluster generated by this example."
}

output "bucket_name" {
  value       = module.development_cluster_backup_restore.bucket_name
  description = "The name of the s3 bucket generated by this example."
}

output "elasticsearch_bastion_instance_public_ip" {
  value       = module.development_cluster_backup_restore.elasticsearch_bastion_instance_public_ip
  description = "The public IP address assigned to the elasticsearch bastion instance generated by this example."
}
