output "bucket_name" {
  value       = module.elasticsearch_cluster_backup.bucket_name
  description = "The name of the S3 bucket generated by this example."
}

output "bucket_domain_name" {
  value       = module.elasticsearch_cluster_backup.bucket_domain_name
  description = "The domain name of the S3 bucket generated by this example."
}

output "elasticsearch_iam_role_name" {
  value       = module.elasticsearch_cluster_backup.elasticsearch_iam_role_name
  description = "The name of the elasticsearch service IAM role generated by this example."
}

output "lambda_iam_role_name" {
  value       = module.elasticsearch_cluster_backup.lambda_iam_role_name
  description = "The name of the lambda IAM role generated by this example."
}

output "lambda_function_name" {
  value       = module.elasticsearch_cluster_backup.lambda_function_name
  description = "The function name of the lambda generated by this example."
}

output "lambda_cloudwatch_event_rule_name" {
  value       = module.elasticsearch_cluster_backup.lambda_cloudwatch_event_rule_name
  description = "The name of the cloudwatch event that triggers the lambda function generated by this example."
}

output "query_lambda_function_name" {
  value       = module.elasticsearch_cluster_backup.query_lambda_function_name
  description = "The function name of the query lambda generated by this example."
}
